# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 45c478defa08c4c5c07f950adbc1aaef5e02a3d614daecc59ba5aace4f19c55dd223ab13d68af767d0b92ca31e7b7b65e87a66c81aaa3ed693554c00ab78569c

test:
  secret_key_base: a8a767e1b322f5deb05a7fda30a4b2256349c219b0692a4bebb238a4503928cb03b3ee38b4f86c596d610249cb8a46107861b92b5edba16dd72ae676a4572f53

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
